# Site settings
title: Welcome to Miichy.Liu's World.
email: miichy.liu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Miichy.Liu And Ice.Ko
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://miichy.github.io" # the base hostname & protocol for your site
twitter_username: chateldon
github_username:  miichy

# Build settings
markdown: kramdown
