# Site settings
title: Welcome to Miichy.Liu's World.

author:
	name : Miichy Liu
	email : miichy.liu@gmail.com
	weibo : chateldon

description: > # this means to ignore newlines until "baseurl:"
  欢迎来到miichy.liu主页。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://miichy.github.io" # the base hostname & protocol for your site
twitter_username: chateldon
github_username:  miichy

# Build settings
markdown: kramdown
